USE codeup_test_db;
INSERT INTO albums(artist, name, release_date, sales, genre)
VALUES ('Michael Jackson', 'Thriller', 1982, 47.3, 'Pop, post-disco, funk and rock'),
       ('AC/DC', 'Back in Black', 1980, 29.4, 'Hard rock'),
       ('Meat Loaf', 'Bat Out of Hell', 1977, 21.7, 'Hard rock, glam rock, heavy metal'),
       ('Pink Floyd', 'The Dark Side of the Moon', 1973, 24.2, 'Progressive'),
       ('Whitney Houston', 'The Bodyguard', 1992, 28.4, 'R&B'),
       ('Eagles', 'Their Greatest Hits (1971-1975)', 1976, 41.2, 'country rock'),
       ('Bee Gees', 'Saturday Night Fever', 1977, 21.6, 'disco'),
       ('Fleetwood Mac', 'Rumours', 1977, 27.9, 'soft rock'),
       ('Shania Twain', 'Come On Over', 1977, 29.6, 'country'),
       ('Various Artists', 'Grease: The Original Sountrack', 1978, 14.4, 'rock and roll'),
       ('Led Zeppelin', 'Led Zeppelin IV', 1971, 29.0, 'hard rock'),
       ('Michael Jackson', 'Bad', 1987, 22.2, 'pop'),
       ('Alanis Morissette', 'Jagged Little Pill', 1995, 24.4, 'alternative rock'),
       ('Michael Jackson', 'Dangerous', 1991, 17.3, 'new jack swing'),
       ('Celine Dion', 'Falling into You', 1996, 20.2, 'pop'),
       ('Eagles', 'Hotel California', 1976, 31.5, 'soft rock'),
       ('The Beatles', 'Sgt. Pepper''s Lonely Hearts Club Band', 1967, 18.2, 'rock'),
       ('Various Artists', 'Dirty Dancing', 1987, 17.9, 'Pop, Rock, R&B'),
       ('Adele', '21', 2011, 25.3, 'Pop, Soul'),
       ('Celine Dion', 'Let''s Talk About Love', 1997, 19.3, 'Pop, Soft Rock'),
       ('The Beatles', '1', 2000, 23.4, 'Rock'),
       ('ABBA', 'Gold: Greatest Hits', 1992, 23.0 , 'Pop, Disco'),
       ('The Beatles', 'Abbey Road', 1969, 14.4, 'Rock'),
       ('Bruce Springsteen', 'Born in the U.S.A.', 1984, 19.6, 'Heartland Rock'),
       ('Dire Straits', 'Brothers in Arms', 1985, 17.7, 'Roots Rock, Blues Rock, Soft Rock'),
       ('James Horner', 'Titanic: Music From the Motion Picture', 1997, 18.1, 'Film Score'),
       ('Metallica', 'Metallica', 1991, 25.2, 'Heavy Metal'),
       ('Nirvana', 'Nevermind', 1991, 16.7, 'Grunge, Alternative Rock'),
       ('Pink Floyd', 'The Wall', 1979, 18.7, 'Progressive Rock'),
       ('Santana', 'Supernatural', 1999, 20.5, 'Latin Rock'),
       ('Madonna', 'The Immaculate', 1990, 19.4, 'Pop, Dance'),
       ('Guns N'' Roses', 'Appetite for Destruction', 1987, 21.9, 'Hard Rock')